sudo: requried 
services: 
  - docker


before_install: 
  - docker build -t ishwo/docker-react1 -f Dockerfile.dev . 

script: 
  - docker run ishwo/docker-react1 npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: " "
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"